### ISSUE TITLE
Link to correct

### ISSUE THREAD

**Issue by rjsj** [VaticanObsSummerSchool2023/lectures#4]
@ivezic : page <https://github.com/VaticanObsSummerSchool2023/lectures/blob/main/IvezicJune7.ipynb>
* The link does not work:<br/> `from [github](https://github.com/ivezic/IRB2023/blob/main/notebooks/IRBclass2.ipynb).`

**Comment by ivezic** [comment]
thanks for reporting! fixed, git pull will get you the fixed version.

**Comment by ivezic** [comment]
Closing.
